# Generated by Django 5.0.7 on 2024-07-18 06:57

import bank_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_remove_userprofile_recipients_iban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_number',
            field=models.CharField(default=bank_app.models.generate_account_number, max_length=11, unique=True),
        ),
    ]
