# Generated by Django 5.0.7 on 2024-07-18 07:03

import bank_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_alter_userprofile_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_number',
            field=models.CharField(default=bank_app.models.generate_account_number, max_length=11),
        ),
    ]
