# Generated by Django 5.0.7 on 2024-07-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
