# Generated by Django 5.0.7 on 2024-07-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0007_userprofile_next_of_kin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linking_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
